# Generated by Django 2.1.1 on 2018-09-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180925_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='m',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
