# Generated by Django 2.1.1 on 2018-09-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180925_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='m',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
